version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/my-project
    docker:
        - image: circleci/node:9-browsers
    steps:
      - checkout
      - restore_cache:
        key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run : npm run webdriver-update-ci
      - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false
workflows:
    build-and-test:
      jobs:
        - build-and-test